input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] == "taskmanager-app" {
    json {
      source => "message"
      target => "app"
    }

    date {
      match => ["[app][@timestamp]", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "taskmanager-app-%{+YYYY.MM.dd}"
  }

  # stdout { codec => rubydebug }
}